// ════════════════════════════════
// 🧩 신규 콘텐츠 로더
// 새 기능 추가할 때, 여기 NEW_CONTENT_FILES 배열에 파일명 한 줄만 추가하면 됨.
// index.html / game.js는 더 이상 안 건드려도 됨.
// ════════════════════════════════



const NEW_CONTENT_FILES = [
  'special-explore.js',
  'recombine-patch.js',
  'fishing.js',
  'sparkle-dust.js',
  'qty-picker.js',
  'forest-explore.js',
  'housing-explore.js',
  'set-explore.js',
  'beach-explore.js',
  'beauty-explore.js',
  'park-explore.js',
  'mystery-explore.js',
  'agency.js',
  'wish-hidden-patch.js',
  'cf-shoot.js',
  'cf-photo.js',
  'cf-guest-fix.js',
  'sfx.js',
  'coupon-patch.js',
  'quest-guide.js',
  'ticket-popup.js',
  'fancafe.js',
  'enhance.js',
  'fan-skills.js',
  'cloud-extra.js',
  'stamina-balance.js',
  'drink-bulk.js',
  'broadcast-expedition.js',
  'fan-rush.js',
  'mat-where.js',
  'goods-gear.js',
  'premium-gacha.js',
  'broadcast-fix.js',
  'premium-cards.js',
  'guide-finger.js',
  'quest-extra.js',
  'shop-coin-sync.js',
  'bond-gift.js',
  'starter-boost.js',
  'newbie-tickets.js',
  'app-resume.js',
  'bgm-btn-fix.js',
  'economy-boost.js',
  'ticket-fragment-fix.js',
  'photolab.js',
  'premium-equip.js',
  'trial-card.js',
  'concert-farm.js',
  'concert-tutorial.js',
  'studio-explore.js',
  'album-studio.js',
  'equip-panel.js',
  'room-themes.js',
  'mystery-unlock.js',
  'quest-concert.js',
  'quest-boost.js',
  'invest.js',
  'stamina-fix.js',
  'square-explore.js',
  'daily-quest.js',
  'trade.js',
  'trap.js',
  'school-fix.js',
  'agency-unlock.js',
  'poca-exp-popup.js',
  'card-exp-boost.js',
  'house-exp-share.js',
  'fan-marker.js',
  'drama.js',
  'kennel.js',
  'kennel-tap.js',
  'kennel-qty.js',
  'kennel-bond.js',
  'meal.js',
  'story-quest.js',
  'clothes-equip.js',
  'skillbook.js',
  'big-drop-popup.js',
  'transcend-aura.js',
];
NEW_CONTENT_FILES.forEach(function(filename) {
  const s = document.createElement('script');
  s.src = filename + '?v=' + Date.now(); // 같은 사이트(GitHub Pages) 경로에서 직접 로드 - raw.githubusercontent.com은 JS 실행이 막힐 수 있음
  document.body.appendChild(s);
});
